### ISSUE TITLE
Block Signing?

### ISSUE THREAD

**Issue by ianpurton** [tdietert/nanocoin#10]
In the description of the block you mention that the block is signed?

In Bitcoin this doesn't happen, is this a way perhaps to generate a coinbase transaction?

Reall nice implementation BTW.

**Comment by tdietert** [comment]
Thanks! I'm not sure what you mean though, in what case would we want to allow the miner to generate a block without the header being signed?

**Comment by ianpurton** [comment]
`data BlockHeader = BlockHeader
  { origin       :: Key.PublicKey -- ^ Public Key of Block miner`

So am I right in thinkoing the miner adds his public key to get paid for mining a block?

And that he also has to sign the block?

**Comment by tdietert** [comment]
Yes, the miner signs the block with the private key corresponding to the public key in the `origin` field.

Currently miners do not "get paid", i.e. they do not receive a reward for mining a block. This is addressed in issue #7, which I may get around to implementing this weekend. It does require adding a new type of transaction though, and the `origin` of the block will determine which address in the network receives the nanocoins.
