### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by tdietert** [tdietert/nanocoin#16]
Currently, the only logging that is being done is sent to STDOUT, with no organized level of importance. A logging module would be desired, using a library with limited dependencies-- all we need is a few levels of severity to choose between, like `Info`, `Warning`, and `Critical`. 

Instead of using `putText`, I would like to be able to write something like `log Warning "log message"`.

**Comment by 0rca** [comment]
Is this library a good fit http://hackage.haskell.org/package/tinylog ?

**Comment by tdietert** [comment]
yeah, that actually looks pretty good!

**Comment by tdietert** [comment]
Functionality added in #19
