### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by tdietert** [tdietert/nanocoin#3]
Add a test suite for:
- De/Serialization tests (To/FromJSON, decode/encode binary) for all manually defined instances.
- more stuff that I can't think of right now...

**Comment by bobbyrauchenberg** [comment]
I've made a start on this with WIP PR: https://github.com/tdietert/nanocoin/pull/20

**Comment by tdietert** [comment]
Thanks! Just keep me up to date when you think it's finished and I'll give it all a thorough look over.

**Comment by bobbyrauchenberg** [comment]
I think this is ready now @tdietert

**Comment by tdietert** [comment]
Initial test suit implemented in PR #24
