### ISSUE TITLE
Multicast to cloud-haskell for P2P 

### ISSUE THREAD

**Issue by tdietert** [tdietert/nanocoin#4]
Currently p2p messaging is done using one-to-many multicast UDP chatter. This means that nodes cannot send messages to individual, specific peer nodes, but must instead broadcast to all nodes at the same time.

It would be nice to add a more sophisticated distributed processing capability to the p2p networking component of nanocoin.

Reference: https://bitbucket.org/dpwiz/distributed-process-p2p/src/1c4a1116d2f029f959b039d8835a22cc3dbf0b66/src/Control/Distributed/Backend/P2P.hs?at=master&fileviewer=file-view-default

**Comment by tdietert** [comment]
In order to implement this a new messaging protocol would have to be developed, not that it would have to change _that_ much.

**Comment by yate** [comment]
Does this mean we can't connect to other nodes across the internet for now?

**Comment by tdietert** [comment]
This does indeed mean you cannot connect to nodes across the internet. Only on the multicast network of the LAN you're connected to. That's why the transition to `cloud-haskell` for networking would be so cool! Then users could spin up their own nodes and interact with the entire network :)

**Comment by Gr1dd** [comment]
Hey guys. I was curious, think maybe a decentralized p2p UDP VPN protocol exists somewhere around github by chance?

I was thinking of docker swarms when this idea popped up: https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/

Could just create a docker image that has a vpn-like torrent or DHT ip protocol for VPN in the dockerfile.

**Comment by Gr1dd** [comment]
I'm trying this out: https://github.com/Gr1dd/TigerCoin-Installer

VPN CONF:

```
[main]
port = 23456
encryption = aescbc
mainkey = 4A34E352D7C32FC42F1CEB0CAA54D40E9D1EEDAF14EBCBCECA429E1B2EF72D21
broadcast = 1.1.1.255
netcidr = 8
recvThreads = 4
sendThreads = 4

[remote "prague"]
ExtIP = 1.1.1.1
LocIP = 1.1.1.2
route = 0.0.0.0/0

[remote "berlin"]
ExtIP = 1.1.1.3
LocIP = 1.1.1.4
route = 0.0.0.0/0

[remote "kiev"]
ExtIP = 1.1.1.5
LocIP = 1.1.1.6
```
This should give 16777214 addresses using default 0.0.0.0/0 route

**Comment by tdietert** [comment]
Finished with PR #29
