### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by tdietert** [tdietert/nanocoin#5]
Currently, there is no configuration file specifying the node config from which to initialize the node on program start. Creating a `Config.hs` and reading from config with `configurator` or something. 

Initially this could be as simple as a json config file to read params like `rpcPort`, `keysDir`, etc.

**Comment by bobbyrauchenberg** [comment]
Added this https://github.com/tdietert/nanocoin/pull/22

Very basic. Just replacing the default settings but letting the command line take precedence as before

**Comment by bobbyrauchenberg** [comment]
Updated with logging in https://github.com/tdietert/nanocoin/pull/27

**Comment by tdietert** [comment]
closing because of PR #35
